# Generated by Django 5.2.14 on 2026-05-25 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeCluster',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeMapping',
            fields=[
                ('pincode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='core.pincodecluster')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=40)),
                ('weight_class', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'Extra Large')], default='large', max_length=10)),
                ('price_inr', models.PositiveIntegerField(default=0)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierReliability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_slip_days', models.FloatField()),
                ('p80_slip_days', models.FloatField()),
                ('sample_size', models.PositiveIntegerField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reliability', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('earliest_date', models.DateField()),
                ('latest_date', models.DateField()),
                ('confidence', models.CharField(max_length=10)),
                ('tier_used', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('actual_delivered_at', models.DateField(blank=True, null=True)),
                ('miss_days', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'indexes': [models.Index(fields=['predicted_at'], name='core_predic_predict_961955_idx'), models.Index(fields=['tier_used'], name='core_predic_tier_us_77b215_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('batch_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('promised_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('received', 'Received'), ('delayed', 'Delayed')], default='scheduled', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_batches', to='core.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'status', 'promised_date'], name='core_produc_product_f38851_idx')],
            },
        ),
        migrations.CreateModel(
            name='LanePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_days', models.FloatField()),
                ('p80_days', models.FloatField()),
                ('p95_days', models.FloatField()),
                ('sample_size', models.PositiveIntegerField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pincodecluster')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'quantity'], name='core_invent_product_ba4f9a_idx')],
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('order_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('shipped_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('transit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pincodecluster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['warehouse', 'cluster'], name='core_delive_warehou_678749_idx'), models.Index(fields=['shipped_at'], name='core_delive_shipped_518ee2_idx')],
            },
        ),
    ]
